# You can use a tool like this to help convert hcl syntax structure to yaml: https://www.hcl2json.com/
#
common:
  subscription_id: "<Insert subscription ID>" # Subscription where the project is de ployed
  tags:
    branch: <branch name>
    classification: pbmm
    cloudusageprofile: "3"
    contact: <some email>; <some email>; etc
    costcentre: "566811"
    env: dev
    owner: <some email>; <some email>; etc
  env: "ScSc"
  group: "CIO"
  project: "ESLZ-light"
  location: "canadacentral"
  Landing-Zone-Next-Hop: 10.140.2.10
  domain:
    private:
      name: cio-dev-eslz-light.local
      registration_enabled: true
    public:
      name: cio-dev-eslz-light.ssc-spc.cloud-nuage.canada.ca

L1_blueprint_base:
  deployOptionalFeatures:
    ddos_protection_plan: false
    defaultRoute: true
    deny_publicip_policy: false
    diagnostics_policy: false
    flow_logs_policy: false
    jumpServer: false
    recovery_services_vault: false
    security_center: false
    sentinel: false
    update_management: false

  optionalFeaturesConfig:
    recovery_services_vault:
      sku: Standard
      soft_delete_enabled: true
    security_center:
      email: some@test.com
      phone: 123-456-7890

  network:
      routes: []
      subnets:
        MAZ:
          - 10.144.196.96/27
        OZ:
          - 10.144.196.32/27
        PAZ:
          - 10.144.196.128/25
        RZ:
          - 10.144.196.64/27
      vnet:
        - 10.144.196.0/24

  L1_RBAC:
    contributorNames: []
    ownerNames:
      - louis-eric.tremblay@ssc-spc.gc.ca
      - bernard.maltais@ssc-spc.gc.ca
    ownerSPNames:
      - Terraform-CIO-Automation-SP
    readerNames: []

  windows_VMs:
    - admin_password: Canada123!
      admin_username: azureadmin
      deploy: false
      encryptDisks: true
      os_managed_disk_type: StandardSSD_LRS
      postfix: "01"
      priority: Spot
      private_ip_address_host: 4
      public_ip: false
      resource_group: Management
      serverType: SWJ
      storage_image_reference:
        offer: WindowsServer
        publisher: MicrosoftWindowsServer
        sku: 2019-Datacenter
        version: latest
      subnet: MAZ
      userDefinedString: RDS
      vm_size: Standard_D4s_v3

L2_blueprint_project:
  RDS-Gateways:
    - 10.101.16.4
  L2_RBAC:
    contributorNames: []
    contributorSPNames: []
    ownerNames: []
    readerNames: []
  windows_VMs:
    - admin_password: Canada123!
      admin_username: azureadmin
      deploy: false
      encryptDisks: true
      os_managed_disk_type: StandardSSD_LRS
      plan:
        name: pro-preview
        product: windows10preview
        publisher: microsoft-hyperv
      postfix: "01"
      priority: Spot
      private_ip_address_host: 6
      resource_group: Management
      serverType: SWJ
      shutdownConfig:
        autoShutdownNotificationStatus: Disabled
        autoShutdownStatus: Enabled
        autoShutdownTime: "17:00"
        autoShutdownTimeZone: Eastern Standard Time
      storage_image_reference:
        offer: windows10preview
        publisher: microsoft-hyperv
        sku: pro-preview
        version: 19041.208.2004162051
      subnet: MAZ
      userDefinedString: maltdev
      vm_size: Standard_D4s_v3
